name: Account
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]
    
env:
  cwd: ${{github.workspace}}/packages/account

defaults:
  run:
    working-directory: packages/account

jobs:
  test-account:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1

      - name: Dependency cache
        uses: actions/cache@v2
        id: cache
        with:
          key: Account-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          path: '**/node_modules'

      # Installs root dependencies, ignoring Bootstrap All script.
      # Bootstraps the current package only
      - run: npm install --ignore-scripts && npm run bootstrap:account
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}
      
      # Builds current package and the ones it depends from.
      - run: npm run build:account
        working-directory: ${{github.workspace}}

      - run: npm run coverage

      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.cwd }}/coverage/lcov.info
          flags: account
        if: ${{ matrix.node-version == 12 }}

      - run: npm run lint

      - run: npm run pack 

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync . s3://my-s3-test-website-bucket